# Generated by Django 3.0.5 on 2020-04-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='products.Product')),
                ('substitute', models.ForeignKey(db_column='substitute_barcode', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_substitutes', to='products.Product')),
            ],
        ),
    ]
